[flake8]
max-line-length = 88

[tool.poetry]
name = "pyurbandict"
version = "0.2.3"
description = "Python wrapper for the Urban Dictionary API."
authors = ["Vitaman02"]
license = "MIT"
homepage = "https://github.com/Vitaman02/pyurbandict"
repository = "https://github.com/Vitaman02/pyurbandict"
keywords = ["urban", "dictionary", "api", "wrapper", "python"]
include = ["README.md"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.28.1"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
flake8 = "^5.0.4"
pre-commit = "^2.20.0"
pytest = "^7.1.2"
pytest-cov = "^3.0.0"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/Vitaman02/pyurbandict/issues"
"Source Code" = "https://github.com/Vitaman02/pyurbandict"
"CI/CD" = "https://github.com/Vitaman02/pyurbandict/actions"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
